Minimizer: MINUIT
MINUIT:
  #doErrors: Pumplin #uncomment to make error bands
  Commands: |
    minimize #uncomment to run the fit
    call fcn 3
    #scan   #uncomment to display chi2 plots for all free parameters in minuit.out.save
    #scan 5 40 -0.5 1.5
    #scan 9 40 0.9 1.0

Parameters:
  Av:  SUMRULE
  #Bv: [ 0.75,0.03]
  #Cv: [ 0.95,0.04,0,10]
  delBv: [ 0., 0.03]
  delCv: [ 0., 0.04]
  delDv: 0.
  As: [ 6.,0.5]
  #Bs: [ 0.5 ,0.1,-1,10]
  #Cs: [ 8,3]
  delBs: 0.
  delCs: [ 0., 3]
  delDs: 0.
  Ag:  SUMRULE
  #Bg:   0.
  #Cg: [ 3,1]
  delBg:    0.
  delCg: [ 0., 1]
  delDg: 0.
  gifl:  0.
  sifl:  1.
  vifl:  2.
  ZERO: [ 0. ]

Parameterisations:
  v:
    class: Fantomas
    parameters: [Av,delBv,delCv,delDv,vifl]
  S:
    class: Fantomas
    parameters: [As,delBs,delCs,delDs,sifl]
  g:
    class: Fantomas
    parameters: [Ag,delBg,delCg,delDg,gifl]

Decompositions:
  pion:
    class: SU3_Pion
    valence: v
    sea: S
    gluon: g

Evolutions:
  positive_pion:
    ? !include evolutions/QCDNUM.yaml
    decomposition: pion
  negative_pion:
    class: FlipCharge
    input: positive_pion
  tungsten_target:
    class: LHAPDF
    set:   nCTEQ15FullNuc_184_74
    member: 0
  proton:
    class: LHAPDF
    set:   nCTEQ15FullNuc_1_1
    member: 0
DefaultEvolution: positive_pion

Q0: 1.378404875209022 #=sqrt(1.9)
alphas: 0.118
Order: NLO
NFlavour: 5
isFFNS: 0
muF: 1.0
muR: 1.0

#Profiler: #uncomment to enable profiling
#  alphas: [ 0.118, 0.119, 0.117 ]
#  Evolutions:
#    tungsten_target:
#      sets:    [nCTEQ15FullNuc_184_74]
#      members: [[0,1,end]]
? !include constants.yaml
#  Status: "On"               # "Off" to turn off profiler
#  WriteTheo: "On"            # Can be "Off", "On" or "Asymmetric" (to store asymmetric variations)
#  getChi2: "Off"              # determine and report chi2 for each variation
#  enableExternalProfiler: "On" # enable creation of additional files, needed for xfitter draw

WriteLHAPDF6:
  name: "xFitterPI"
  authors: "xFitter Developers' team: Ivan Novikov, Hamed Abdolmaleki, Daniel Britzger, Amanda Cooper-Sarkar, Francesco Giuli, Alexander Glazov, Aleksander Kusina, Agnieszka Luszczak, Fred Olness, Pavel Starovoitov, Mark Sutton, Oleksandr Zenaiev"
  description: "Minimal parameterisation. NLO negative pion fitted to Drell-Yan data of experiments NA10 and E615 and prompt photon production data of experiment WA70. Nuclear PDF set nCTEQ15FullNuc_184_74 was used for tungsten target."

ExtraActions:
  PrintPionMoments:
