Minimizer: MINUIT
MINUIT:
  #doErrors: Hesse #uncomment to make error bands
  Commands: |
    minimize #uncomment to run the fit
    call fcn 3

Parameters:
  Nv: 0.662735 
  Bv: 0.0282693 
  Cv: 0.840956 
  Dv: 0.47627
  As: [ 0.909654, 0.1]
  Bs: -5.52823
  Cs: 2.78696
  Ds: 3.359
  Es: -0.748
  Fs: 1.10012
  Gs: 1.89568
  Ng: 0.902012 
  Bg: -2.36061
  Cg: 1.71977
  Dg: 1.29227
  Eg: -1.00642
  Fg: 0.091581
  Gg: 0.794874
  Hg: 1.27646
  Av: SUMRULE
  Ag: SUMRULE
  Ns: 1

Parameterisations:
  v:
    class: Expression
    expression: "Nv*Av*(1+Bv*x^(1/2))*(1-x)^(Cv)*x^(Dv)"
  S:
    class: Expression
    expression: "(As*exp(Bs+Cs*(ln(1/x))^(1/2))*(1-x)^(Ds)*(1+Es*(x)^(1/2)+Fs*x))/(ln(1/x))^(Gs)"
  g:
    class: Expression
    expression: "Ag*((Ng*exp(Bg+Cg*(ln(1/x))^(1/2))+(Dg+Eg*(x)^(1/2)+Fg*x)*x^(Gg))*(1-x)^(Hg))"

Decompositions:
  pion:
    class: SU3_NegativePion
    valence: v
    sea: S
    gluon: g

Evolutions:
  negative_pion:
    ? !include evolutions/QCDNUM.yaml
    decomposition: pion
  positive_pion:
    class: FlipCharge
    input: negative_pion
  tungsten_target:
    class: LHAPDF
    set:   nCTEQ15FullNuc_184_74
    member: 0
  proton:
    class: LHAPDF
    set:   nCTEQ15FullNuc_1_1
    member: 0
DefaultEvolution: negative_pion

Q0: 1.378404875209022 #=sqrt(1.9)
alphas: 0.118
Order: NLO
NFlavour: 5
isFFNS: 0
muF: 1.0
muR: 1.0

#Profiler: #uncomment to enable profiling
#  alphas: [ 0.118, 0.119, 0.117 ]
#  Evolutions:
#    tungsten_target:
#      sets:    [nCTEQ15FullNuc_184_74]
#      members: [[0,1,end]]
? !include constants.yaml

WriteLHAPDF6:
  name: "xFitterPI"
  authors: "xFitter Developers' team: Ivan Novikov, Hamed Abdolmaleki, Daniel Britzger, Amanda Cooper-Sarkar, Francesco Giuli, Alexander Glazov, Aleksander Kusina, Agnieszka Luszczak, Fred Olness, Pavel Starovoitov, Mark Sutton, Oleksandr Zenaiev"
  description: "Minimal parameterisation. NLO negative pion fitted to Drell-Yan data of experiments NA10 and E615 and prompt photon production data of experiment WA70. Nuclear PDF set nCTEQ15FullNuc_184_74 was used for tungsten target."

ExtraActions:
  PrintPionMoments:
